name: Build APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build APK
        run: |
          mkdir app
          echo "<h1>APK OK</h1>" > app/index.html
          zip -r app.apk app

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app.apk
